# Generated by Django 4.2.2 on 2023-06-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="feature_image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
