# Generated by Django 4.2.2 on 2023-06-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_app", "0004_alter_clinic_feature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_datetime",
            field=models.DateTimeField(),
        ),
    ]
