# Generated by Django 4.2.1 on 2023-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("feature_image", models.ImageField(upload_to="images/")),
                ("description", models.TextField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("heart", "Heart Center"),
                            ("neuro", "Neuroscience Center"),
                            ("obesity", "Obesity Center"),
                            ("eye", "Eye Center"),
                            ("ortho", "Orthopedic Center"),
                            ("pediatric", "Pediatric Center"),
                        ],
                        max_length=10,
                    ),
                ),
                ("established_at", models.DateField()),
            ],
        ),
    ]
