# Generated by Django 4.2.2 on 2023-06-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_age',
            field=models.IntegerField(max_length=200),
        ),
    ]
