# Generated by Django 4.2.2 on 2023-06-10 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='established_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='department',
            field=models.CharField(choices=[('Heart Center', 'Heart Center'), ('Neuroscience Center', 'Neuroscience Center'), ('Obesity Center', 'Obesity Center'), ('Eye Center', 'Eye Center'), ('Orthopedic Center', 'Orthopedic Center'), ('Pediatric Center', 'Pediatric Center')], max_length=300),
        ),
    ]
