# Generated by Django 4.2 on 2023-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='department',
            field=models.CharField(blank=True, choices=[('Heart Center', 'Heart Center'), ('Neuroscience Center', 'Neuroscience Center'), ('Obesity Center', 'Obesity Center'), ('Eye Center', 'Eye Center'), ('Orthopedic Center', 'Orthopedic Center'), ('Pediatric Center', 'Pediatric Center')], max_length=50, null=True),
        ),
    ]
