# Generated by Django 4.2.2 on 2023-06-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_availableappointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.CharField(choices=[('2.30 Pm', '2.30 Pm'), ('1.30 Pm', '1.30 Pm'), ('3.30 Pm', '3.30 Pm'), ('11.00 Pm', '11.00 Pm'), ('11.30 Pm', '10.30 Pm'), ('4.30 Pm', '4.30 Pm'), ('4.00 Pm', '4.00 Pm'), ('12.00 Pm', '12.00 Pm'), ('10.30 Pm', '10.30 Pm'), ('10.00 Pm', '10.00 Pm'), ('2.00 Pm', '2.00 Pm'), ('3.00 Pm', '3.00 Pm'), ('5.30 Pm', '5.30 Pm'), ('5.00 Pm', '5.00 Pm'), ('12.30 Pm', '12.30 Pm'), ('1.00 Pm', '1.00 Pm')], max_length=30),
        ),
        migrations.DeleteModel(
            name='AvailableAppointments',
        ),
    ]
